# ============================================================
# 頻道設定 - 每個 channel 對應一個 Discord Webhook
# accounts: Twitter @帳號名稱列表（不含 @）
# webhook_env: 對應的 GitHub Secret 名稱
# ============================================================

CHANNELS = [
    {
        "name": "illustrators",
        "webhook_env": "WEBHOOK_ILLUSTRATORS",
        "accounts": [
            "homutan1",
            "Akefumi305",
            "Jin_Yu0810",
            "aiaiai_1133",
            "Mochii0709",
            "HOSHIBACKYARD",
            "Kokoya_art",
            "Ohoo_7am",
            "p1ct0a1",        # ⚠️ 同時在 ai-creators
            "CarmesJocelin",
            "Dino_illus",
            "asteroid_ill",
            "sathishkumar_27",
            "gracile_jp",
            "key_999",
            "yu_yiming",
            "qry1028_",
            "pomesubrus",
            "hayasabro",
            "JL_T4N",
            "kieed23232",
            "BGAsylum",
            "dolosseXD",
            "nezukonezu32",
            "wooupp",
        ],
    },
    {
        "name": "VRC",
        "webhook_env": "WEBHOOK_VRC",
        "accounts": [
            "Min_VPhoto",
            "toraba___",
            "yunomi_VRC",
            "riplint",
            "SVK1891",
            "haiki1112",
            "sukutou2025",
            "W_IS_A_BEL",
            "fusefinal",
            "shinji_vrc",
            "VRChatKUMA",
            "komaEE_uwu_",
            "RinneTokyo",
            "TAKUMIN_35",
            "hisai_s",
            "mesabuaka",
            "avoc4_",
            "FIn0170",
            "OXI_DuuuuuuLL",
            "yokovrc",
            "CBET_0000",
            "memonoshi",
            "too_ka444",
            "Rem0512_VRC",
            "_uancoe",
            "ESMR_01",
            "titan_otoufuVRC",
            "kuromi6_6",
        ],
    },
    {
        "name": "video-creators",
        "webhook_env": "WEBHOOK_VIDEO_CREATORS",
        "accounts": [
            "APO_PLUS_",
            "birdman46049238",
            "zzzz_jinnn",
            "HarlequinWheels",
            "CAT02A",
            "oshiruko_s2",
        ],
    },
    {
        "name": "3d-modelers",
        "webhook_env": "WEBHOOK_3D_MODELERS",
        "accounts": [
            "SGY_MR_92",
            "nothing_3d",
            "jarvinart",
            "janurschel",
            "MRubinkowski",
            "Sakura_Rabbiter",
        ],
    },
    {
        "name": "graphic-design",
        "webhook_env": "WEBHOOK_GRAPHIC_DESIGN",
        "accounts": [
            "15424578268",
            "Amememe929",
        ],
    },
    {
        "name": "photography",
        "webhook_env": "WEBHOOK_PHOTOGRAPHY",
        "accounts": [
            "kolshicako",
            "taru153",
            "rako_bear_",
            "Raylivez1",
            "hanasakimakura",
            "tanco_camera",
            "2025pics",
        ],
    },
    {
        "name": "ai-creators",
        "webhook_env": "WEBHOOK_AI_CREATORS",
        "accounts": [
            "keshiAIart",
            "p1ct0a1",         # ⚠️ 同時在 illustrators
            "WorldSaboten",
            "naf_aiart",
            "748cm",
            "Yoshi58581128",
            "ai_chan_niji",
            "okomechan991",
            "eatsleep1111",
            "G_Eskeles",
            "MaxVOAO",
        ],
    },
]
